### ISSUE TITLE
Add /health endpoint

### ISSUE THREAD

**Issue by shumsky** [rcruzper/express-actuator#2]
Hi,

What do you think about adding /health endpoint like in Sprint Boot 2 (https://docs.spring.io/spring-boot/docs/2.0.0.RC2/actuator-api/html/#health-retrieving)?

**Comment by rcruzper** [comment]
I added the /health endpoint just with the status UP, I will try to add some other information as diskSpace or db connection.
Thanks for your suggestion :)
