### ISSUE TITLE
Custom health endpoint

### ISSUE THREAD

**Issue by etruta** [rcruzper/express-actuator#21]
A possibility to customize the health endpoint.

**Comment by rcruzper** [comment]
could you tell some examples?

**Comment by etruta** [comment]
Depending on kubernetes config the health endpoint is healthz or status.

Maybe setting the health endpoint in config, like:

```
const options = {
    basePath: '/management',
    health: {
        endpoint: '/status'
    }
};
```

**Comment by rcruzper** [comment]
You can configure kubernetes to use the endpoint you want as readiness or liveness probe: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-a-liveness-http-request

```yaml
readinessProbe:
      httpGet:
        path: /management/health
```
