### ISSUE TITLE
Interface to custom endpoints

### ISSUE THREAD

**Issue by rmalveis** [rcruzper/express-actuator#28]
Hi!
I really liked the simplicity of this project.

As Spring actuator already knows, sometimes we want custom endpoints for monitoring dependencies or to show another info that is important in our case scenario. 
What you think about custom endpoints made by the user?

(maybe some of them can become standard out of the box, but keep this flexible while the standard versions does not exists seems useful)

**Comment by rcruzper** [comment]
Thanks for the PR, it makes sense :)

**Comment by rcruzper** [comment]
Waiting documentation update

**Comment by rmalveis** [comment]
I can work on this tomorrow.

**Comment by rcruzper** [comment]
I do appreciate your commits.

**Comment by rmalveis** [comment]
Hey, when are you thinking to release the new version? I see in npm that you bumped to 1.5.0 already, but I can't download it yet.

**Comment by rcruzper** [comment]
it should be available. I've just tried.

**Comment by rmalveis** [comment]
Oh.. nevermind.. I'm behind a nexus npm proxy and by some reason it is not finding the new version.. 
Thanks

**Comment by rcruzper** [comment]
you should be able to force the download by: npm install express-actuator@1.5.0

**Comment by rmalveis** [comment]
Yeah.. but the Nexus npm proxy was down and it was returning that version
1.5.0 does not exist. Even forcing with @1.5.0.
But it is okay now. The proxy is now connecting to the npm registry to let
me download the new version.

Thank you again.
Cheers.

Rafael M. Ximenes

Em qua, 1 de abr de 2020 15:33, Raúl Cruz <notifications@github.com>
escreveu:
