### ISSUE TITLE
Allow overriding default endpoints

### ISSUE THREAD

**Issue by fodor0205** [rcruzper/express-actuator#39]
Allow overriding default endpoints (for example `/health`) with a custom controller definition.

A possible implementation is using the existing `customEndpoints` array in a backwards-incompatible way like in #37.

**Comment by rcruzper** [comment]
Thanks for the contribution

**Comment by fsher** [comment]
Thank you so much for adding this! Really looking forward to using this functionality, once released! 👍

**Comment by rcruzper** [comment]
published on 1.7.0 :)
