### ISSUE TITLE
Clarify style/linting guide

### ISSUE THREAD

**Issue by fodor0205** [rcruzper/express-actuator#40]
In [CONTRIBUTING.md](https://github.com/rcruzper/express-actuator/blob/master/CONTRIBUTING.md#submitting-a-pull-request) there is a section about style guide:

> Follow the [style guide](https://standardjs.com/) which is using standard.

But project is using [eslint:recommended](https://github.com/rcruzper/express-actuator/blob/master/.eslintrc#L2) during [pretest](https://github.com/rcruzper/express-actuator/blob/master/package.json#L32).

Running `npx standard` in the project directory produces 1001 linting errors.

**Comment by rcruzper** [comment]
Thank you for the advice
