### ISSUE TITLE
Registration to Spring boot admin

### ISSUE THREAD

**Issue by AnthonyNTK** [rcruzper/express-actuator#46]
Any documentation on how to register the app to Spring boot admin?

**Comment by rcruzper** [comment]
Hi,

this is something that is not implemented. I didn't think in this feature but I will take it into account for the future. Even better, if you think you could help to implement it, it would be nice :)

**Comment by rcruzper** [comment]
I was looking how Spring Boot deals with this register/deregister feature from Spring Boot Admin (SBA) and it looks like there is another dependency called spring-boot-admin-starter-client which is the responsible to register the app into SBA.

I have also found that python has a dependency called pyctuator which merge the actuator and SBA registration features.

Right now I think that the best way to deal with this request is to create another npm package to implement it, but I will track this issue in my backlogto  give it a more deeply though
