### ISSUE TITLE
add prometheus endpoint 

### ISSUE THREAD

**Issue by Leocete** [rcruzper/express-actuator#47]
Hello! In our project, we need to implement a smth like `prometheus` endpoint in Spring actuator (https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-features.html). Should we create a custom endpoint for that or there is a build-in property where it could be specified?

**Comment by rcruzper** [comment]
Hi,

there is no built-in property for this endpoint. 
I will add it to the list of future features, however I never worked with this specific endpoint with spring, if you create a custom endpoint it would be awesome if you can add it as a new endpoint to this project :)
