### ISSUE TITLE
Properties parser parses some git commit IDs as numbers

### ISSUE THREAD

**Issue by TimSBSquare** [rcruzper/express-actuator#48]
If you have a git short ID like:
* 296e115
* 3324244
Then both of those are parsed as numbers and returned as numbers from the endpoint. This is not great but less of an issue with the second. However the first one is treated as an exponential and in my case rendered as "2.96e+117".

**Comment by rcruzper** [comment]
Oh thanks, I didn't notice this problem. 
I've been testing the app and it is something related with the dependency in charge of read the properties file. It read the git.commit.id.abbrev as a number if it has an "e" (from scientific notation)
After spending some time I didn't find any way to avoid this behaivor so I could try another dependency or I could change from properties file to json format...
