### ISSUE TITLE
how can I see the detail for health endpoints?

### ISSUE THREAD

**Issue by Sai0514** [rcruzper/express-actuator#65]
![1653881644(1)](https://user-images.githubusercontent.com/22516098/170912486-dee9b805-a0ab-463d-a2e5-3a474a832f64.png)

yeah, I want to return some health endpoint details for my node sever by express-actuator middleware, but it can only return { status: 'up' }, no show-detail parameter. 
Could you give me some suggestions? 
Thank you very much！

**Comment by rcruzper** [comment]
I didn't implement this behaviour yet, but you can create your own custom endpoint to set any detail information: https://github.com/rcruzper/express-actuator#custom-endpoints. I will try to implement it in the future
